"""General project specific constants, filepaths and helper functions."""

# import os
from pathlib import Path

#=============================================================================
# File paths

DATA_FOLDER = 'data/'
# NICKY You could swap the line above with the comment and you could have the stuff work nicely with drive.
# DATA_FOLDER = '/content/drive/MyDrive/ml/data'

MODELS_FOLDER = 'models/'

# Contains all given training data
RAW_TRAIN_DATA_FOLDER = DATA_FOLDER + 'training/'
# Contains all given test data. To be used for generating AIcrowd submission.
RAW_TEST_DATA_FOLDER = DATA_FOLDER + 'test_set_images/'


# Folder to contain all our data that was generated by our preprocessing.
PROCESSED_DATA_FOLDER = DATA_FOLDER + 'processed/'

# Not too sure what this is for
REORDERED_DATA_FOLDER = PROCESSED_DATA_FOLDER + 'reordered/'
# To contain the data preprocessed in the manner we want it for cross validation. Not used for now
CROSSVAL_DATA_FOLDER = PROCESSED_DATA_FOLDER + 'crossval/'
# To contain the final version of data to be used for training out final model.
FINAL_DATA_FOLDER = PROCESSED_DATA_FOLDER + 'final/'



RAW_TEST_PREDICTIONS_FOLDER = 'data/test_set_predictions/'



#=============================================================================
# Helper functions

def create_missing_directories():
    """
    Creates all needed directories that don't exist yet.
    """

    FOLDERS = [
        DATA_FOLDER,
        RAW_TRAIN_DATA_FOLDER,
        RAW_TEST_DATA_FOLDER,
        PROCESSED_DATA_FOLDER,
        # REORDERED_DATA_FOLDER,
        # CROSSVAL_DATA_FOLDER,
        FINAL_DATA_FOLDER+'images/',
        FINAL_DATA_FOLDER+'labels/',
        RAW_TEST_PREDICTIONS_FOLDER
    ]

    for folder in FOLDERS:
        Path(folder).mkdir(parents=True, exist_ok=True)
